[tool.pytest.ini_options]
fitness_warnings = [
    # Format: (target_package, restriction_type (all|only), exceptions)
    {"search_path"=".", "target_package"="modules.payment", "type"="all", "exceptions"=[]}
]
